### ISSUE TITLE
Can you provide the checkpoint for test?

### ISSUE THREAD

**Issue by Rhett98** [IRMVLab/TransLO#1]

**Comment by liujiuming123** [comment]
Thank you for your ackonwledgement of our work. Checkpoint is now too large to release here. If possible, we can send it to you through e-mail.

**Comment by Rhett98** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已收到你的邮件，我查看后会尽快给你回复。

**Comment by Rhett98** [comment]
Here is my email: 373914367@qq.com Thank you!

**Comment by Smezzdl1996** [comment]
can you email me the checkpoint file please, my email address is smezzdl@163.com. Wish you the best

**Comment by Rhett98** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已收到你的邮件，我查看后会尽快给你回复。

**Comment by liujiuming123** [comment]
Well, we have sent the ckpt through the email.

**Comment by Rhett98** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已收到你的邮件，我查看后会尽快给你回复。

**Comment by qlsinori** [comment]
Here is my email: 514793418@qq.com Thank you!

**Comment by Rhett98** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已收到你的邮件，我查看后会尽快给你回复。

**Comment by hu-xue** [comment]
Here is my email: 1091392557@qq.com Thank you!

**Comment by Rhett98** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已收到你的邮件，我查看后会尽快给你回复。

**Comment by hu-xue** [comment]
> Well, we have sent the ckpt through the email.

hi! thanks for this great work! can you share with me the checkpoint file by email? 1091392557@qq.com  thanks a lot!

**Comment by HandsomeLizh** [comment]
> Here is my email: [514793418@qq.com](mailto:514793418@qq.com) Thank you!

Thanks for this great work! can you share with me the checkpoint file by email? [1590602734@qq.com](mailto:1590602734@qq.com) thanks a lot!

**Comment by yuyangpoi** [comment]
Here is my email: 1652380932@qq.com, Thank you!
